### ISSUE TITLE
有没有办法可以解密AssetBundle文件？

### ISSUE THREAD

**Issue by nijinekoyo** [chinosk6/gkms-meta-dec#1]
简单试了一下发现一部分AssetBundle文件可以通过补全版本号`2022.3.21f1`来解包，但是还有大部分文件似乎文件头部分存在加密
想问一下有没有办法可以解密

**Comment by chinosk6** [comment]
有大佬做了，可以看看 [gkmasToolkit](https://github.com/kishidanatsumi/gkmasToolkit) 这个仓库

**Comment by nijinekoyo** [comment]
感谢

**Comment by nijinekoyo** [comment]
简单阅读项目后大概确定，解密代码应该是在这边
https://github.com/kishidanatsumi/gkmasToolkit/blob/a6394a43434570143a5848f6cd758a9fab8ede32/MaskedHeaderStream.py#L128

但是其中的`maskString`参数不是很清楚是如何获得的，他似乎是传入了`md5NameDict[md5]`了，`md5NameDict`似乎是由某个清单文件获得的，但是不知道如何正确获得这个文件，源代码内似乎是从`idolypride`游戏目录获取的

**Comment by chinosk6** [comment]
gkmas 和 ip 都是 qa 的，解密方式都差不多。清单文件就在游戏数据目录 `files/octo/pdb/400/25000/octocacheevai`

**Comment by nijinekoyo** [comment]
> gkmas 和 ip 都是 qa 的，解密方式都差不多。清单文件就在游戏数据目录 `files/octo/pdb/400/25000/octocacheevai`

感谢，才看见大佬的回复
仿造[gkmasToolkit](https://github.com/kishidanatsumi/gkmasToolkit)写了个解密工具[Gakuen-idolmaster-ab-decrypt](https://github.com/nijinekoyo/Gakuen-idolmaster-ab-decrypt)

**Comment by nijinekoyo** [comment]
![image](https://github.com/chinosk6/gakuen-idolmaster-global-metadata-decrypt/assets/125987288/d90edac6-3e52-4914-a38d-6e6f0024f0fd)
解完才发现似乎也不是完全正确的，其他数据都可以提取，但是图片会全部出错，很奇怪

**Comment by Epiceagle** [comment]
大佬我只能解包167个文件 是不是我操作有问题
